### ISSUE TITLE
Required LLVM 3.6

### ISSUE THREAD

**Issue by rdebath** [Lisapple/BF-Compiler-Tutorial-with-LLVM#1]
This is not the most recent released version.

If you follow the LLVM releases religiously the most recent release is 3.7.
If you follow your distribution the most recent release may be 3.5 or 3.4 (or earlier).
Distributions still include version 2.7.

All these releases are incompatible with each other, but only in the (massive amounts of) boilerplate needed AFAICS.

You need to cover this or you're already out of date.

**Comment by Lisapple** [comment]
You're right, when I created this tutorial, I used the last release version of LLVM (3.6), I updated the tutorial and the sources (commit: ac955c03df) to support newest LLVM versions.
Thanks for the issue.
